### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by OSUANSDNC** [tsinghua-fib-lab/UV-SAM#1]
你好 我在运行你的代码时出现的以下问题：
![image](https://github.com/tsinghua-fib-lab/UV-SAM/assets/104304932/f8fe8f41-a983-4a2f-90f5-7f81804c97a7)
请问您之前有遇到过吗

**Comment by huoyiru** [comment]
seg_path_pretrained='/mmsegmentation-main/pretrain/mmseg_new.pth',##put the path of the SegFormer pretrained model here

**Comment by OSUANSDNC** [comment]
请问seg_path_pretrained='/mmsegmentation-main/pretrain/mmseg_new.pth',##put the path of the SegFormer pretrained model here的链接可以分享一下吗

**Comment by Xin-Zh00** [comment]
> 你好 我在运行你的代码时出现的以下问题： ![image](https://private-user-images.githubusercontent.com/104304932/298267538-f8fe8f41-a983-4a2f-90f5-7f81804c97a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MDY5NTcsIm5iZiI6MTcwNTkwNjY1NywicGF0aCI6Ii8xMDQzMDQ5MzIvMjk4MjY3NTM4LWY4ZmU4ZjQxLWE5ODMtNGEyZi05MGY1LTdmODE4MDRjOTdhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQwNjU3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTcxN2Q1MTUwNDM4ZDY1Yzc2YWE0ZTczNjM1MGFiZmQzMzA3YjNiZDgzZjU1YzQyNDA4MDIwNmMyZWJjNTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UHqcVARIPE_DyeLv36-RocmcoYwHgYPdSNjripsCxTY) 请问您之前有遇到过吗

不好意思，没遇到过，可能是环境问题？

**Comment by Xin-Zh00** [comment]
> 请问seg_path_pretrained='/mmsegmentation-main/pretrain/mmseg_new.pth',##put the path of the SegFormer pretrained model here的链接可以分享一下吗

这个模型参数是mmseg的，去他的GitHub仓库下载即可

**Comment by NYB-AAA** [comment]
你好，我也遇到了这个问题，请问你是怎么解决的
