### ISSUE TITLE
数据集大小以及复现问题

### ISSUE THREAD

**Issue by Yi-Heng** [tsinghua-fib-lab/UV-SAM#10]
请问为什么论文中数据集大小与下载的数据集大小不一样，论文中北京区域卫星影像2,491，而下载的北京影像为554张，并且训练精度为60.91，请问是否是因为下载的北京数据集为整体数据集的子集导致的精度不高呢

wandb: Run summary:
wandb:               epoch 99
wandb:                loss 0.11191
wandb:      lr-AdamW-1/pg1 0.0
wandb:      lr-AdamW-1/pg2 0.0
wandb:      lr-AdamW-1/pg3 0.0
wandb:        lr-AdamW/pg1 0.0
wandb:        lr-AdamW/pg2 0.0
wandb:        lr-AdamW/pg3 0.0
wandb:            max_grad 0.11475
wandb:            min_grad 0.00054
wandb:       train_acc_seg 98.47717
wandb:          train_loss 0.11191
wandb:      train_loss_SAM 0.07326
wandb:       train_loss_ce 0.03865
wandb: trainer/global_step 8599
wandb:           valaacc_0 0.92438
wandb:            valacc_0 0.97279
wandb:            valacc_1 0.68954
wandb:            valiou_0 0.91428
wandb:            valiou_1 0.60911
wandb:           valmacc_0 83.12
wandb:           valmiou_0 76.17
wandb:
wandb: You can sync this run to the cloud by running:
wandb: wandb sync results/SegSAMPLerEmbMLP/logs/wandb/offline-run-20240418_223613-dwxa2v3y
wandb: Find logs at: results/SegSAMPLerEmbMLP/logs/wandb/offline-run-20240418_223613-dwxa2v3y/logs

**Comment by Yi-Heng** [comment]
wandb:               epoch 99
wandb:                loss 0.03048
wandb:      lr-AdamW-1/pg1 0.0
wandb:      lr-AdamW-1/pg2 0.0
wandb:      lr-AdamW-1/pg3 0.0
wandb:        lr-AdamW/pg1 0.0
wandb:        lr-AdamW/pg2 0.0
wandb:        lr-AdamW/pg3 0.0
wandb:            max_grad 0.20034
wandb:            min_grad 0.00108
wandb:       train_acc_seg 99.2713
wandb:          train_loss 0.03048
wandb:      train_loss_SAM 0.01367
wandb:       train_loss_ce 0.01681
wandb: trainer/global_step 3299
wandb:           valaacc_0 0.93763
wandb:            valacc_0 0.98901
wandb:            valacc_1 0.66466
wandb:            valiou_0 0.93029
wandb:            valiou_1 0.62799
wandb:           valmacc_0 82.68
wandb:           valmiou_0 77.91
xian数据集上的精度，也有问题

**Comment by Xin-Zh00** [comment]
We download the satellite images with a resolution of 256×256 pixels and stitch them into 1024×1024 images. The number of images in the table is the total number of 256×256 images used for training and testing. We have carefully explained this in the section of Datasets.
