### ISSUE TITLE
How to perform with  other datasets?

### ISSUE THREAD

**Issue by zhangda1018** [tsinghua-fib-lab/UV-SAM#4]
Hi, good work!
I want to perform your model on other remote sensing datasets, but the resolution is 1500×1500. I'm a new hand, so I want ask how to modify your code to adjust another datasets? 
Do I just only need to modify config .py? 
Another question, wiil you transfer this model to other datasets or give other examples?
Thanks very much!

**Comment by NYB-AAA** [comment]
请问你解决这个问题了吗

**Comment by Xin-Zh00** [comment]
Please refer to other mmseg or RSPrompter codes.

**Comment by Xin-Zh00** [comment]
> Hi, good work! I want to perform your model on other remote sensing datasets, but the resolution is 1500×1500. I'm a new hand, so I want ask how to modify your code to adjust another datasets? Do I just only need to modify config .py? Another question, wiil you transfer this model to other datasets or give other examples? Thanks very much!

Hi, thanks for your question. You can modify the config.py file to adjust the dataset. You need to modify the dataset path, the number of classes, and the input size. Additionally, you need to modify the datatset.py to adjust the model. You can refer to the mmsegmentation documentation for more details.
