### ISSUE TITLE
> 请问mmseg_new.pth的下载地址是什么

### ISSUE THREAD

**Issue by sun-0704** [tsinghua-fib-lab/UV-SAM#8]
> 请问seg_path_pretrained='/mmsegmentation-main/pretrain/mmseg_new.pth',##put the path of the SegFormer pretrained model here的链接可以分享一下吗

这个模型参数是mmseg的，去他的GitHub仓库下载即可

_Originally posted by @big-boss26 in https://github.com/tsinghua-fib-lab/UV-SAM/issues/1#issuecomment-1903373099_

**Comment by Xin-Zh00** [comment]
I have updated the README.md file. The pretrained model and trained model can be downloaded from the following link: *[Google Drive](https://drive.google.com/drive/folders/1szict970v0Z7LrY78jPQkNG1UzTHT1gb?usp=sharing)*.
